CREATE    TABLE PUBLIC.LAYER_GROUPS (
          ID UUID NOT NULL DEFAULT UUID_GENERATE_V4 () PRIMARY KEY,
          CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          CREATED_BY UUID REFERENCES PUBLIC.PROFILES,
          UPDATED_AT TIMESTAMPTZ,
          UPDATED_BY UUID REFERENCES PUBLIC.PROFILES,
          IS_ARCHIVED BOOL DEFAULT FALSE,
          LAYER_ID UUID REFERENCES PUBLIC.LAYERS ON DELETE CASCADE,
          NAME VARCHAR NOT NULL,
          DESCRIPTION VARCHAR,
          ROLE_ID UUID REFERENCES PUBLIC.ROLES NOT NULL,
          IS_ADMIN BOOL DEFAULT FALSE,
          IS_DEFAULT BOOLEAN DEFAULT FALSE
          );

-- Changes 05/01/23 ---
ALTER     TABLE PUBLIC.ASSIGNMENT_GROUPS
RENAME TO LAYER_GROUPS;

ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      CONSTRAINT ASSIGNMENT_GROUPS_ASSIGNMENT_ID_FKEY;

ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      COLUMN ASSIGNMENT_ID;

ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN LAYER_ID UUID REFERENCES PUBLIC.LAYERS;

-- Changes 05/08/23
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN NAME VARCHAR NOT NULL;

ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN DESCRIPTION VARCHAR;

-- Changes 5/24/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       CONSTRAINT LAYER_GROUPS_CREATED_BY_FKEY FOREIGN KEY (CREATED_BY) REFERENCES PUBLIC.PROFILES (ID);

-- Changes 6/9/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      CONSTRAINT LAYER_GROUPS_GROUP_ID_FKEY,
ADD       CONSTRAINT LAYER_GROUPS_GROUP_ID_FKEY FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUPS ON DELETE CASCADE;

ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      CONSTRAINT LAYER_GROUPS_LAYER_ID_FKEY,
ADD       CONSTRAINT LAYER_GROUPS_LAYER_ID_FKEY FOREIGN KEY (LAYER_ID) REFERENCES PUBLIC.LAYERS ON DELETE CASCADE;

-- Changes 6/13/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN ROLE_ID UUID REFERENCES PUBLIC.ROLES NOT NULL;

ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      CONSTRAINT LAYER_GROUPS_GROUP_ID_FKEY;

ALTER     TABLE PUBLIC.LAYER_GROUPS
DROP      COLUMN GROUP_ID;

-- Changes 7/26/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN IS_ARCHIVED BOOL DEFAULT FALSE;

-- Changes 10/2/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN IS_ADMIN BOOL DEFAULT FALSE;

-- Changes 11/30/23 --
ALTER     TABLE PUBLIC.LAYER_GROUPS
ADD       COLUMN IS_DEFAULT BOOLEAN DEFAULT FALSE;
