-- drop policy "Enable ALL access for authenticated users" on "public"."organization_groups";
--
-- drop policy "Enable ALL access for authenticated users" on "public"."project_groups";
--
-- drop policy "Enable ALL access for authenticated users" on "public"."projects";
--
--
